### ISSUE TITLE
Ajout d'une page pour les dons

### ISSUE THREAD

**Issue by Linzo99** [Tariha/xassida.sn-fontend#1]
##  Description :
Actuellement, notre projet open source ne dispose pas d'une page dédiée permettant aux utilisateurs de faire des dons pour soutenir son développement continu. Je propose l'ajout d'une nouvelle page de don sur le site du projet afin de permettre aux utilisateurs et aux contributeurs de contribuer financièrement.

**NB**: Utilisation de **PayTech** si possible

**Comment by dmd99** [comment]
Il est important de fournir aux utilisateurs une option facile et transparente pour contribuer financièrement à votre projet. Votre idée d'utiliser PayTech comme moyen de traitement des dons est particulièrement pertinente, par conséquent, j'aimerais me pencher l'integration d'une page de dons sur votre site tout en garantissannt une expérience utilisateur fluide et agréable. Je prendrais en compte vos recommandations lors de ce processus afin de créer une solution qui réponde aux besoins de votre communauté.

**Comment by Linzo99** [comment]
> Il est important de fournir aux utilisateurs une option facile et transparente pour contribuer financièrement à votre projet. Votre idée d'utiliser PayTech comme moyen de traitement des dons est particulièrement pertinente, par conséquent, j'aimerais me pencher l'integration d'une page de dons sur votre site tout en garantissannt une expérience utilisateur fluide et agréable. Je prendrais en compte vos recommandations lors de ce processus afin de créer une solution qui réponde aux besoins de votre communauté.

Merci beaucoup pour cette réaction, je vais vous assigner la tâche.
